# Working with Known JSON Schemas

## Introduction
You've started taking a look at JSON files and you'll continue to explore how to navigate and traverse these files. One common use case of json files will be when you are connecting to various websites through their established APIs to retrieve data from them. With these, you are typically given a schema for how the data is structured and then will use this knowledge to retrieve pertinent information. In this lecture, you'll take a look at the response from the NY Times API.

## Objectives
You will be able to:

* Use the JSON module to load and parse JSON documents
* Write data to predefined JSON schemas
* Convert JSON to a pandas dataframe

## Reading a JSON Schema

Here's the JSON schema provided for a section of the NY Times API:
<img src="images/schema_overview.png" width="400">

or a more detailed view (truncated):

<img src="images/schema_detailed.png" width="500">

You can see that the master structure is a dictionary and has a key named 'response'. This is also a dictionary and has two keys: 'data' and 'meta'. As you continue to examine the schema hierarchy, you'll notice the vast majority, in this case, are dictionaries.

## Loading the Data File

As you saw before, let's start by importing this data from the file. Here's how to open the file and load its contents.

In [1]:
import json

In [2]:
f = open('ny_times_response.json', 'r')
data = json.load(f)

In [3]:
print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['status', 'copyright', 'response'])

You should see that there are two additional keys 'status' and 'copyright' which were not shown in the schema documentation.

## Loading Specific Data

Looking at the schema, you might be interested in retrieving a specific piece of data, such as the articles' headlines. Notice that this is a key under **'docs'**, which is under 'response'. So the schema is roughly: **data['response']['docs']['headline']**. While this is close to the code you'll use to extract headlines, something is a bit off. Notice that if you look closely at the schema outline, that the 'docs' subheading is actually a list. Each item within this list should be a dictionary with the keys shown above, but that is an important distinction. Breaking it into two steps you have:

In [6]:
data['response']

{'docs': [{'web_url': 'https://query.nytimes.com/gst/abstract.html?res=9C05E3D7113DE633A25754C1A9679D946597D6CF',
   'snippet': 'Spent $22,200',
   'abstract': 'Spent $22,200',
   'print_page': '2',
   'blog': {},
   'source': 'The New York Times',
   'multimedia': [],
   'headline': {'main': "HIGGINS, SPENT $22,189.53.; Governor-Elect's Election Expenses -- Harrison $9,220.28.",
    'kicker': None,
    'content_kicker': None,
    'print_headline': None,
    'name': None,
    'seo': None,
    'sub': None},
   'keywords': [{'name': 'persons',
     'value': 'HIGGINS, LT. GOV.',
     'rank': 0,
     'major': None}],
   'pub_date': '1904-11-17T00:00:00Z',
   'document_type': 'article',
   'type_of_material': 'Article',
   '_id': '4fc04eb745c1498b0d23da00',
   'word_count': 213,
   'score': 1},
  {'web_url': 'https://query.nytimes.com/gst/abstract.html?res=9E07E6DA1F3BE433A25750C2A9669D946593D6CF',
   'snippet': '',
   'print_page': '15',
   'blog': {},
   'source': 'The New York Times',
   'multimedia': [],
   'headline': {'main': 'GARDEN BOUTS CANCELED; Mauriello Says He Could Not Be Ready on Nov. 3',
    'kicker': '1',
    'content_kicker': None,
    'print_headline': None,
    'name': None,
    'seo': None,
    'sub': None},
   'keywords': [],
   'pub_date': '1944-10-23T00:00:00Z',
   'document_type': 'article',
   'type_of_material': 'Article',
   '_id': '4fc21ebf45c1498b0d612b22',
   'word_count': 149,
   'score': 1},
  {'web_url': 'https://query.nytimes.com/gst/abstract.html?res=9E07E1DB1330E531A15756C1A9639C946492D6CF',
   'snippet': 'Stock prices last week, on the lightest volume of the year, sustained the largest losses in about two months. Some technicians were inclined to believe that if offerings became heavier on the decline, the averages could challenge the lows of the f...',
   'print_page': 'F1',
   'blog': {},
   'source': 'The New York Times',
   'multimedia': [],
   'headline': {'main': 'Stock Drop Is Biggest in 2 Months--Margin Rise Held Factor in Lightest Trading of 1955',
    'kicker': '1',
    'content_kicker': None,
    'print_headline': None,
    'name': None,
    'seo': None,
    'sub': None},
   'keywords': [],
   'pub_date': '1955-05-15T00:00:00Z',
   'document_type': 'article',
   'byline': {'original': 'By JOHN G. FORREST',
    'person': [{'firstname': 'John',
      'middlename': 'G.',
      'lastname': 'FORREST',
      'qualifier': None,
      'title': None,
      'role': 'reported',
      'organization': '',
      'rank': 1}],
    'organization': None},
   'type_of_material': 'Article',
   '_id': '4fc3b41d45c1498b0d7fd41e',
   'word_count': 823,
   'score': 1},
  {'web_url': 'https://query.nytimes.com/gst/abstract.html?res=9504EEDE123BE733A25755C0A9679D946597D6CF',
   'snippet': 'The first public rehearsal and concert of the Philharmonic Society will be given at Carnegie Hall on Friday afternoon and Saturday evening. Gustav F. Kogel, the former director of the Museum Concert at Frankfort-on-the-Main, will be the conductor....',
   'abstract': 'Healy, Michael, will suit',
   'print_page': '20',
   'blog': {},
   'source': 'The New York Times',
   'multimedia': [],
   'headline': {'main': 'MUSIC OF THE WEEK',
    'kicker': None,
    'content_kicker': None,
    'print_headline': None,
    'name': None,
    'seo': None,
    'sub': None},
   'keywords': [{'name': 'persons',
     'value': 'HEALY, MICHAEL',
     'rank': 0,
     'major': None}],
   'pub_date': '1904-11-06T00:00:00Z',
   'document_type': 'article',
   'type_of_material': 'Article',
   '_id': '4fc04eb745c1498b0d23da12',
   'word_count': 2609,
   'score': 1},
  {'web_url': 'https://www.nytimes.com/1992/05/06/business/anacomp-inc-reports-earnings-for-qtr-to-march-31.html',
   'snippet': '',
   'print_page': '20',
   'blog': {},
   'source': 'The New York Times',
   'multimedia': [],
   'headline': {'main': 'Anacomp Inc. reports earnings for Qtr to March 31',
    'kicker': None,
    'content_kicker': None,
    'print_headline': None,
    'name': None,
    'seo': None,
    'sub': None},
   'keywords': [{'name': 'subject',
     'value': 'COMPANY EARNINGS',
     'rank': 0,
     'major': None}],
   'pub_date': '1992-05-06T00:00:00Z',
   'document_type': 'article',
   'news_desk': 'Financial Desk',
   'type_of_material': 'Statistics',
   '_id': '4fd1b3018eb7c8105d6d690a',
   'word_count': 129,
   'score': 1},
  {'web_url': 'https://query.nytimes.com/gst/abstract.html?res=9503EFDF153DE53ABC4C51DFB4678389669EDE',
   'snippet': '',
   'print_page': 'S9',
   'blog': {},
   'source': 'The New York Times',
   'multimedia': [],
   'headline': {'main': 'Brooklyn Routs Yeshiva',
    'kicker': '1',
    'content_kicker': None,
    'print_headline': None,
    'name': None,
    'seo': None,
    'sub': None},
   'keywords': [],
   'pub_date': '1972-12-24T00:00:00Z',
   'document_type': 'article',
   'type_of_material': 'Article',
   '_id': '4fc47bb045c1498b0da03363',
   'word_count': 144,
   'score': 1},
  {'web_url': 'https://query.nytimes.com/gst/abstract.html?res=9F03E1DA1631E63BBC4D51DFB4678389669EDE',
   'snippet': 'ALBUQUERQUE, N. M., Dec. 24 -- Holiday drinkers who have drunk too much can get free rides home from now until Jan. 2 through a test program being carried out by taxi companies, university students and a local alcohol safety organization.  ',
   'print_page': '11',
   'blog': {},
   'source': 'The New York Times',
   'multimedia': [],
   'headline': {'main': 'Albuquerque Program Gives Drinkers a Lift',
    'kicker': '1',
    'content_kicker': None,
    'print_headline': None,
    'name': None,
    'seo': None,
    'sub': None},
   'keywords': [],
   'pub_date': '1972-12-25T00:00:00Z',
   'document_type': 'article',
   'byline': {'original': 'Special to The New York Times',
    'person': [{'firstname': None,
      'middlename': None,
      'lastname': None,
      'qualifier': None,
      'title': None,
      'role': 'reported',
      'organization': '',
      'rank': 1}],
    'organization': None},
   'type_of_material': 'Article',
   '_id': '4fc47bb045c1498b0da03367',
   'word_count': 151,
   'score': 1},
  {'web_url': 'https://query.nytimes.com/gst/abstract.html?res=9905E6DD153EE03BBC4C51DFB667838F659EDE',
   'snippet': '',
   'print_page': '1',
   'blog': {},
   'source': 'The New York Times',
   'multimedia': [],
   'headline': {'main': 'Front Page 7 -- No Title',
    'kicker': '1',
    'content_kicker': None,
    'print_headline': None,
    'name': None,
    'seo': None,
    'sub': None},
   'keywords': [],
   'pub_date': '1944-10-24T00:00:00Z',
   'document_type': 'article',
   'type_of_material': 'Front Page',
   '_id': '4fc21ebf45c1498b0d612b3c',
   'word_count': 29,
   'score': 1},
  {'web_url': 'https://query.nytimes.com/gst/abstract.html?res=9507EFDB1F3AE733A25755C0A96E9C946597D6CF',
   'snippet': 'The employers and the unions have lined up in preparation for a long fight in the building war. An indication of the feeling that this will be a real fight is the appointment of a regular Press Committee by the employers. Members of their associat...',
   'abstract': "housesmiths won't strike",
   'print_page': '1',
   'blog': {},
   'source': 'The New York Times',
   'multimedia': [],
   'headline': {'main': 'UNIONS AND BUILDERS READY FOR LONG FIGHT; None of the Strikers Back - Lock-Out Soon in Effect. 23,000 ALREADY INVOLVED Orders Sent to Every Building Employer Within Twenty-five Miles -- House-smiths Vote Not to Strike.',
    'kicker': None,
    'content_kicker': None,
    'print_headline': None,
    'name': None,
    'seo': None,
    'sub': None},
   'keywords': [{'name': 'glocations',
     'value': 'NEW YORK CITY',
     'rank': 0,
     'major': None},
    {'name': 'subject', 'value': 'STRIKES', 'rank': 0, 'major': None},
    {'name': 'subject',
     'value': 'PENN. MINERS THREATEN',
     'rank': 0,
     'major': None},
    {'name': 'subject',
     'value': 'BLDG. TRADES EMP. ASS. MAY LOCK OUT 30,000',
     'rank': 0,
     'major': None},
    {'name': 'subject',
     'value': '23,000 MEN INVOLVED',
     'rank': 0,
     'major': None}],
   'pub_date': '1904-08-06T00:00:00Z',
   'document_type': 'article',
   'type_of_material': 'Front Page',
   '_id': '4fc04eb745c1498b0d23da17',
   'word_count': 883,
   'score': 1}],
 'meta': {'hits': 15533655, 'offset': 0, 'time': 207}}

In [5]:
docs = data['response']['docs']
print(type(docs), len(docs))

<class 'list'> 9

In [6]:
for doc in docs:
    print(doc['headline'])

{'main': "HIGGINS, SPENT $22,189.53.; Governor-Elect's Election Expenses -- Harrison $9,220.28.", 'kicker': None, 'content_kicker': None, 'print_headline': None, 'name': None, 'seo': None, 'sub': None}
{'main': 'GARDEN BOUTS CANCELED; Mauriello Says He Could Not Be Ready on Nov. 3', 'kicker': '1', 'content_kicker': None, 'print_headline': None, 'name': None, 'seo': None, 'sub': None}
{'main': 'Stock Drop Is Biggest in 2 Months--Margin Rise Held Factor in Lightest Trading of 1955', 'kicker': '1', 'content_kicker': None, 'print_headline': None, 'name': None, 'seo': None, 'sub': None}
{'main': 'MUSIC OF THE WEEK', 'kicker': None, 'content_kicker': None, 'print_headline': None, 'name': None, 'seo': None, 'sub': None}
{'main': 'Anacomp Inc. reports earnings for Qtr to March 31', 'kicker': None, 'content_kicker': None, 'print_headline': None, 'name': None, 'seo': None, 'sub': None}
{'main': 'Brooklyn Routs Yeshiva', 'kicker': '1', 'content_kicker': None, 'print_headline': None, 'name': None, 'seo': None, 'sub': None}
{'main': 'Albuquerque Program Gives Drinkers a Lift', 'kicker': '1', 'content_kicker': None, 'print_headline': None, 'name': None, 'seo': None, 'sub': None}
{'main': 'Front Page 7 -- No Title', 'kicker': '1', 'content_kicker': None, 'print_headline': None, 'name': None, 'seo': None, 'sub': None}
{'main': 'UNIONS AND BUILDERS READY FOR LONG FIGHT; None of the Strikers Back - Lock-Out Soon in Effect. 23,000 ALREADY INVOLVED Orders Sent to Every Building Employer Within Twenty-five Miles -- House-smiths Vote Not to Strike.', 'kicker': None, 'content_kicker': None, 'print_headline': None, 'name': None, 'seo': None, 'sub': None}

Or if you want to just print the main headlines themselves:

In [7]:
for doc in docs:
    print(doc['headline']['main'])
    print('\n')

HIGGINS, SPENT $22,189.53.; Governor-Elect's Election Expenses -- Harrison $9,220.28.


GARDEN BOUTS CANCELED; Mauriello Says He Could Not Be Ready on Nov. 3


Stock Drop Is Biggest in 2 Months--Margin Rise Held Factor in Lightest Trading of 1955


MUSIC OF THE WEEK


Anacomp Inc. reports earnings for Qtr to March 31


Brooklyn Routs Yeshiva


Albuquerque Program Gives Drinkers a Lift


Front Page 7 -- No Title


UNIONS AND BUILDERS READY FOR LONG FIGHT; None of the Strikers Back - Lock-Out Soon in Effect. 23,000 ALREADY INVOLVED Orders Sent to Every Building Employer Within Twenty-five Miles -- House-smiths Vote Not to Strike.

## Transforming JSON to Alternative Formats

You've also previously started to take a look at how to transform JSON to DataFrames. Investigating the schema, a good option for this could again be the 'docs' subheading. While this still has nested data itself, it's often easier to load the entire section as a dataframe and then use additional functions to break apart the internally nested data from there.

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame(data['response']['docs'])
df.head(3)

,_id,abstract,blog,byline,document_type,headline,keywords,multimedia,news_desk,print_page,pub_date,score,snippet,source,type_of_material,web_url,word_count
0,4fc04eb745c1498b0d23da00,"Spent $22,200",{},NaN,article,"{'main': 'HIGGINS, SPENT $22,189.53.; Governor...","[{'name': 'persons', 'value': 'HIGGINS, LT. GO...",[],NaN,2,1904-11-17T00:00:00Z,1,"Spent $22,200",The New York Times,Article,https://query.nytimes.com/gst/abstract.html?re...,213
1,4fc21ebf45c1498b0d612b22,NaN,{},NaN,article,{'main': 'GARDEN BOUTS CANCELED; Mauriello Say...,[],[],NaN,15,1944-10-23T00:00:00Z,1,,The New York Times,Article,https://query.nytimes.com/gst/abstract.html?re...,149
2,4fc3b41d45c1498b0d7fd41e,NaN,{},"{'original': 'By JOHN G. FORREST', 'person': [...",article,{'main': 'Stock Drop Is Biggest in 2 Months--M...,[],[],NaN,F1,1955-05-15T00:00:00Z,1,"Stock prices last week, on the lightest volume...",The New York Times,Article,https://query.nytimes.com/gst/abstract.html?re...,823

## Breaking out nested data

Now that you have the data loaded, it's time to clean it up by breaking out some of the nested data. For example, you should notice that the headline entries are actualy dictionaries. You could transform these into singular data columns with something like this:

In [10]:
keys = df.headline.iloc[0].keys() #Get dictionary keys
#Keep track of columns we make for subsequent preview
new_cols = []
#Create a new feature for each of these keys
for key in keys:
    new_col = 'headline_{}'.format(key) #Create new column name
    df[new_col] = df.headline.map(lambda x: x[key]) #Create a new column
    new_cols.append(new_col)
df[new_cols].head()

,headline_main,headline_kicker,headline_content_kicker,headline_print_headline,headline_name,headline_seo,headline_sub
0,"HIGGINS, SPENT $22,189.53.; Governor-Elect's E...",None,None,None,None,None,None
1,GARDEN BOUTS CANCELED; Mauriello Says He Could...,1,None,None,None,None,None
2,Stock Drop Is Biggest in 2 Months--Margin Rise...,1,None,None,None,None,None
3,MUSIC OF THE WEEK,None,None,None,None,None,None
4,Anacomp Inc. reports earnings for Qtr to March 31,None,None,None,None,None,None

Wahoo! This is a good general strategy for transforming nested JSON: create a DataFrame and then break out nested features into their own column features.

## Outputing to JSON

Finally, take a look at how you can write data back to JSON. Like loading, you first open a file (this time with write permission) and use the json package to transfer data to that file container.

In [11]:
with open('output.json', 'w') as f:
    json.dump(data, f)

## Summary
There you have it! In this, you took another look at JSON, taking a look at an example schema diagram and retrieving information. You also looked at a general procedure for transforming nested data to Pandas DataFrames (create a DataFrame, and then break apart nested data using lambda functions to create additional columns). Finally, you also took a brief look at saving data to json files.